main: it.lucalumetti.sharplay.indigo.IndigoBlockBan.IndigoBlockBan
name: IndigoBlockBan
version: 0.1b
commands:
   IndigoBlockBan:
     permission: IndigoBlockBan.admin
     description: Comando principale
     aliases: [ibb]
